module Chronicle
  module Packs
    enum PackBehaviorKind
      Behavior
      LLM
      Relation
    end

    # Behavior execution context handed to pack behavior handlers. Carries
    # the triggering pack's canonical settings plus a cross-pack settings
    # lookup (Form 2 `ctx.settings` / Form 3 `ctx.pack_settings`).
    class BehaviorContext
      getter pack_name : String
      getter settings : Hash(String, JSON::Any)
      @settings_provider : Proc(String, Hash(String, JSON::Any)?)

      def initialize(
        @pack_name : String,
        @settings : Hash(String, JSON::Any),
        @settings_provider : Proc(String, Hash(String, JSON::Any)?),
      )
      end

      def pack_settings(pack_name : String) : Hash(String, JSON::Any)?
        @settings_provider.call(pack_name)
      end
    end

    # A pack-local behavior. Handlers are closures generated by the DSL that
    # call the annotated methods; the loader renames these to their canonical
    # `{pack}.{name}` form and registers them per-runtime.
    class PackBehavior
      getter kind : PackBehaviorKind
      getter name : String
      getter event_types : Array(String)
      getter where : Hash(String, JSON::Any)?
      getter priority : Int32
      getter creates : Array(String)
      getter pattern : String?
      getter relation_type : String?
      getter description : String
      getter model : String?
      getter prompt_template : String?
      getter max_tokens : Int32
      getter temperature : Float64
      getter max_tool_turns : Int32
      getter tools : Array(String)
      getter pack_owner : String?

      getter handler : Proc(Event, GraphProjection, BehaviorContext, Nil)?
      getter relation_handler : Proc(GraphRelation, Event, GraphProjection, BehaviorContext, Nil)?
      getter llm_handler : Proc(Event, GraphProjection, BehaviorContext, String, Nil)?

      def initialize(
        @name : String,
        @event_types : Array(String) = [] of String,
        @where : Hash(String, JSON::Any)? = nil,
        @priority : Int32 = 0,
        @creates : Array(String) = [] of String,
        @pattern : String? = nil,
        @relation_type : String? = nil,
        @description : String = "",
        @model : String? = nil,
        @prompt_template : String? = nil,
        @max_tokens : Int32 = 4096,
        @temperature : Float64 = 0.7,
        @max_tool_turns : Int32 = 6,
        @tools : Array(String) = [] of String,
        @handler : Proc(Event, GraphProjection, BehaviorContext, Nil)? = nil,
        @relation_handler : Proc(GraphRelation, Event, GraphProjection, BehaviorContext, Nil)? = nil,
        @llm_handler : Proc(Event, GraphProjection, BehaviorContext, String, Nil)? = nil,
        @kind : PackBehaviorKind = PackBehaviorKind::Behavior,
        @pack_owner : String? = nil,
      )
      end

      # Whether this behavior subscribes to the given event. `on` empty means
      # any event; `where` (dotted paths against the event payload) must pass.
      def matches?(event : Event) : Bool
        return false unless event_types.empty? || event_types.includes?(event.type)
        where = @where
        return true if where.nil?

        Packs.where_matches?(where, event.payload)
      end

      # Canonical copy with the pack prefix applied and ownership stamped.
      def canonicalize(pack : Pack, settings : Hash(String, JSON::Any)) : PackBehavior
        copy = PackBehavior.new(
          name: "#{pack.name}.#{@name}",
          event_types: @event_types.dup,
          where: @where,
          priority: @priority,
          creates: @creates.dup,
          pattern: @pattern,
          relation_type: @relation_type,
          description: description_for(pack),
          model: @model,
          prompt_template: @prompt_template,
          max_tokens: @max_tokens,
          temperature: @temperature,
          max_tool_turns: @max_tool_turns,
          tools: resolve_tools(pack),
          handler: @handler,
          relation_handler: @relation_handler,
          llm_handler: @llm_handler,
          kind: @kind,
          pack_owner: pack.name,
        )
        copy
      end

      # Compose the effective description from the decorator's `description=`
      # plus the pack's same-named prompt body (upstream `_resolve_description`).
      def description_for(pack : Pack) : String
        parts = [] of String
        parts << @description.strip unless @description.empty?
        pack.prompts.each do |prompt|
          if prompt.name == @name
            parts << prompt.body.strip
            break
          end
        end
        parts.join("\n\n")
      end

      # Rename pack-local tool references on this behavior to canonical form.
      private def resolve_tools(pack : Pack) : Array(String)
        @tools.map do |tool|
          if tool.starts_with?("#{pack.name}.")
            tool
          else
            "#{pack.name}.#{tool}"
          end
        end
      end
    end
  end
end
