require "./clarity/errors"
require "./clarity/clock"
require "./clarity/content_hash"
require "./clarity/event"
require "./clarity/json_compare"
require "./clarity/json_converters"
require "./clarity/ids"
require "./clarity/event_log"
require "./clarity/event_log_codec"
require "./clarity/event_store"
require "./clarity/run_projection"
require "./clarity/routing"
require "./clarity/routing_config"
require "./clarity/graph_projection"
require "./clarity/patterns"
require "./clarity/graph_store"
require "./clarity/effect"
require "./clarity/effect_artifact"
require "./clarity/llm_cache"
require "./clarity/tool_cache"
require "./clarity/tool_permission"
require "./clarity/tool"
require "./clarity/session_store"
require "./clarity/behavior_runner"
require "./clarity/replay"
require "./clarity/sans_io/http"
require "./clarity/approval"
require "./clarity/platform_edge"
require "./clarity/sink"
require "./clarity/config"
require "./clarity/provider_catalog"
require "./clarity/channel"
require "./clarity/model_executor"
require "./clarity/log_agent"
require "./clarity/telemetry"
require "./clarity/diff_formatter"
require "./clarity/tui"
require "./clarity/runtime"
require "./clarity/view"
require "./clarity/frame"
require "./clarity/sqlite_event_store"
require "./clarity/store_url"
require "./clarity/cli"

# Log-primary primitives for deterministic agent execution.
module Clarity
  VERSION = "0.1.0"
end
